
CREATE TABLE IF NOT EXISTS repository (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  uuid CHAR(36) UNIQUE NOT NULL,
  type VARCHAR(100) NOT NULL,
  url VARCHAR(256) NOT NULL,
  auth_token VARCHAR(100)
);
