

CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid CHAR(36) UNIQUE
);

CREATE TABLE IF NOT EXISTS repository (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid CHAR(36) UNIQUE,
  name varchar(500),
  is_active INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS repository_settings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES user ON DELETE CASCADE,
  repo_id INTEGER NOT NULL REFERENCES repository ON DELETE CASCADE,
  color char(6),
  is_favorite INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS repository_author_merging (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES user ON DELETE CASCADE,
  repo_id INTEGER NOT NULL REFERENCES repository ON DELETE CASCADE,
  merging_config TEXT
);

